### ISSUE TITLE
A Small Suggestion

### ISSUE THREAD

**Issue by y1-fan** [silent-dxx/typst-color-emoji#1]
Thank you for this tool!!

I found that commonly emojis (as fonts) are aligned on the bottom line but your tool align them with letters.

![图片](https://github.com/silent-dxx/typst-color-emoji/assets/78839187/e4515900-e768-4287-9746-bea8bfc6e2ad)

I think it's a good idea to add `baseline: 20%` in box like this:
```
#let t-cm(id) = box(baseline: 20%)[
  #image(width: 1.0em, "twemoji/assets/svg/" + id + ".svg")
]
```
and the emojis will be rendered like this:
![图片](https://github.com/silent-dxx/typst-color-emoji/assets/78839187/f5e8ffd6-2c94-483e-bce6-545e4efc225a)

That would be better, right? 🤔

**Comment by silent-dxx** [comment]
Thank you for your support!

After careful consideration of your feedback, I have adjusted the alignment of emoji output and found a suitable value to make the emoji and text appear more harmonious. For details, please refer to [Adjust emonji image for baseline alignment](https://github.com/silent-dxx/typst-color-emoji/commit/806dde7982dd7542528ed41d488ce3821770d255)

![PixPin_2024-01-27_20-00-53](https://github.com/silent-dxx/typst-color-emoji/assets/6861105/ba6e9baf-c91a-4929-99d1-8c4298a0448c)

In addition, some emojis in OpenMoji are inherently smaller, so it may appear as if there is no bottom alignment. This phenomenon is normal.

**Comment by y1-fan** [comment]
That's great. Thanks a lot! ☺️

**Comment by y1-fan** [comment]
That's great. Thanks a lot! 😄
